// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Core__Option from "@rescript/core/src/Core__Option.res.mjs";
import * as HubNodejs from "@farcaster/hub-nodejs";

var client = Core__Option.map(process.env.HUB_URL, (function (prim) {
        return HubNodejs.getSSLHubRpcClient(prim);
      }));

var FrameRequest = {};

async function handler(req, res) {
  console.log("req: ", req);
  var match = req.method;
  if (match === "POST") {
    console.log(req.query);
  } else {
    res.headers.set("Allow", "POST");
  }
}

export {
  client ,
  FrameRequest ,
  handler ,
}
/* client Not a pure module */
